{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac195648",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "********* Menu **********\n",
      "   --- SISTEMA DE ALUNOS ---\n",
      "    1 - Inserir Aluno\n",
      "    2 - Listar turma e Estatísticas\n",
      "    3 - Buscar aluno por nome\n",
      "    4 - Alterar dados de um aluno\n",
      "    5 - Excluir um aluno\n",
      "    6 - Finalizar programa\n",
      "    ------------------------\n",
      "Somente números inteiros!\n",
      "Inserir aluno\n"
     ]
    }
   ],
   "source": [
    "lista_nomes=[]\n",
    "lista_pesos=[]\n",
    "lista_altura=[]\n",
    "lista_imc=[]\n",
    "\n",
    "def inserir_aluno():\n",
    "    print('Inserir aluno')\n",
    "\n",
    "    nome=input('\\nDigite nome do Aluno: ')\n",
    "    lista_nomes.append(nome)\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            peso=float(input(\"\\nDigite o peso do Aluno: \"))\n",
    "            lista_pesos.append(peso)\n",
    "            break\n",
    "        except:\n",
    "            print(\"\\nDigite somente peso válido!\")\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            altura=float(input(\"\\nDigite a altura do Aluno: \"))\n",
    "            lista_altura.append(altura)\n",
    "            break\n",
    "        except:\n",
    "            print(\"\\nDigite somente altura válida!\")\n",
    "\n",
    "    imc = peso / (altura * altura)\n",
    "    lista_imc.append(imc)\n",
    "\n",
    "    print(\"\\nAluno inserido com sucesso!\")\n",
    "\n",
    "\n",
    "def listar_turma():\n",
    "    print(\"\\nListar e Estatísticas\")\n",
    "\n",
    "    if len(lista_nomes) == 0:\n",
    "        print(\"Nenhum aluno cadastrado.\")\n",
    "        return\n",
    "\n",
    "    for i in range(len(lista_nomes)):\n",
    "        print(lista_nomes[i], lista_pesos[i], lista_altura[i], lista_imc[i])\n",
    "\n",
    "    mediapeso = sum(lista_pesos)/len(lista_pesos)\n",
    "    mediaimc = sum(lista_imc) / len(lista_imc)\n",
    "\n",
    "    print(f\"Média de peso: {mediapeso:.2f}\")\n",
    "    print(f\"Média de IMC: {mediaimc:.2f}\")\n",
    "\n",
    "\n",
    "def buscar_aluno():\n",
    "    buscarnome = input(\"Busque o Aluno Desejado: \").lower()\n",
    "\n",
    "    encontrado = False\n",
    "\n",
    "    for i in range(len(lista_nomes)):\n",
    "        if lista_nomes[i].lower() == buscarnome:\n",
    "            print(f\"Nome: {lista_nomes[i]}\")\n",
    "            print(f\"Peso: {lista_pesos[i]}\")\n",
    "            print(f\"Altura: {lista_altura[i]}\")\n",
    "            print(f\"IMC: {lista_imc[i]:.2f}\")\n",
    "            encontrado = True\n",
    "            break\n",
    "\n",
    "    if not encontrado:\n",
    "        print(\"Aluno não encontrado!\")\n",
    "\n",
    "\n",
    "def alterar_dados():\n",
    "    if len(lista_nomes) == 0:\n",
    "        print(\"Nenhum aluno para alterar.\")\n",
    "        return\n",
    "\n",
    "    nome = input('Digite nome do aluno a alterar: ')\n",
    "\n",
    "    if nome not in lista_nomes:\n",
    "        print(\"Aluno não encontrado.\")\n",
    "        return\n",
    "\n",
    "    indice = lista_nomes.index(nome)\n",
    "\n",
    "    print(f\"Alterando dados de {nome}:\")\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            peso=float(input(\"Novo peso: \"))\n",
    "            break\n",
    "        except:\n",
    "            print(\"Peso inválido!\")\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            altura=float(input(\"Nova altura: \"))\n",
    "            break\n",
    "        except:\n",
    "            print(\"Altura inválida!\")\n",
    "\n",
    "    imc = peso / (altura * altura)\n",
    "\n",
    "    lista_pesos[indice] = peso\n",
    "    lista_altura[indice] = altura\n",
    "    lista_imc[indice]   = imc\n",
    "\n",
    "    print(\"Dados alterados com sucesso!\")\n",
    "\n",
    "\n",
    "def excluir_aluno():\n",
    "    if len(lista_nomes) == 0:\n",
    "        print(\"Nenhum aluno para excluir.\")\n",
    "        return\n",
    "\n",
    "    nome = input('Digite nome do aluno para excluir: ')\n",
    "\n",
    "    if nome not in lista_nomes:\n",
    "        print(\"Aluno não encontrado.\")\n",
    "        return\n",
    "\n",
    "    indice = lista_nomes.index(nome)\n",
    "\n",
    "    del lista_nomes[indice]\n",
    "    del lista_altura[indice]\n",
    "    del lista_pesos[indice]\n",
    "    del lista_imc[indice]\n",
    "\n",
    "    print(\"Aluno excluído com sucesso!\")\n",
    "\n",
    "\n",
    "def menu():\n",
    "    print('********* Menu **********')\n",
    "    print('''   --- SISTEMA DE ALUNOS ---\n",
    "    1 - Inserir Aluno\n",
    "    2 - Listar turma e Estatísticas\n",
    "    3 - Buscar aluno por nome\n",
    "    4 - Alterar dados de um aluno\n",
    "    5 - Excluir um aluno\n",
    "    6 - Finalizar programa\n",
    "    ------------------------''')\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            opcao=int(input('\\nDigite Opção: '))\n",
    "            if opcao <1 or opcao > 6:\n",
    "                print('Digite uma opção válida!')\n",
    "            else:\n",
    "                return opcao\n",
    "        except:\n",
    "            print('Somente números inteiros!')\n",
    "\n",
    "\n",
    "\n",
    "#início do Programa\n",
    "while True:\n",
    "    opcao = menu()\n",
    "\n",
    "    if opcao == 1:\n",
    "        inserir_aluno()\n",
    "    elif opcao == 2:\n",
    "        listar_turma()\n",
    "    elif opcao == 3:\n",
    "        buscar_aluno()\n",
    "    elif opcao == 4:\n",
    "        alterar_dados()\n",
    "    elif opcao == 5:\n",
    "        excluir_aluno()\n",
    "    elif opcao == 6:\n",
    "        print(\"Finalizar Programa\")\n",
    "        break"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
